FW_Version_Initialization: FW_Version_Initialization.o
	gcc -o FW_Version_Initialization FW_Version_Initialization.o -ltspi
FW_Version_Initialization.o: FW_Version_Initialization.c
	gcc -c FW_Version_Initialization.c

clean:
	rm -f FW_Version_Initialization FW_Version_Initialization.o
